### ISSUE TITLE
nptd isn't started and enabled

### ISSUE THREAD

**Issue by MarcoWeiss** [saltstack-formulas/ntp-formula#11]
Hi all,

i'm new to salt and GitHub today but i have a first request.
On the ntp-formular i can't see a functionality that starts the ntpd and enabling it as service.

Can you add something like the service section i added below in the init.sls ?

``` yaml
{% from "ntp/map.jinja" import ntp with context %}

ntp:
  pkg:
    - installed
    - name: {{ ntp.client }}

{% set ntp_conf_src = salt['pillar.get']('ntp:ntp_conf') -%}

{% if ntp_conf_src %}
ntp_conf:
  file:
    - managed
    - name: {{ ntp.ntp_conf }}
    - template: jinja
    - source: {{ ntp_conf_src }}
    - require:
      - pkg: ntp

  service:
    - name: {{ ntp.service }}
    - running
    - enable: True
    - watch:
      - file: {{ ntp.ntp_conf }}
    - require:
      - pkg: ntp
{% endif %}
```
