### ISSUE TITLE
jinja rendering issues

### ISSUE THREAD

**Issue by techdragon** [saltstack-formulas/ntp-formula#5]
```
    Data failed to compile:
----------
    Rendering SLS ntp failed, render error: expected token ',', got ':'; line 12 in template:
```

I had to strip back init.sls to 

```
ntp:
  pkg:
    - installed

ntpd_conf:
  file.managed:
    - name: /etc/ntp.conf
    - source: salt://ntp/ntp-client.conf
    - require:
      - pkg: ntp
```

before it would render.
